---
title: "Zadanie 2"
output: html_document
---

Zad. 1
```{r}
crypto <- readRDS("crypto.rds")
#head(crypto, 30)
#1.2. Wiersze dotyczące bitcoina
unique(crypto$Currency)
crypto <- crypto[grepl("bitcoin", crypto$Currency, ignore.case = TRUE),]
unique(crypto$Currency)
#1.3. Kolumny Date i Close
crypto <- crypto[c("Date", "Close")]
#head(crypto)
#1.4. Zmiana typu kolumny Date na date
# Sys.setlocale("LC_TIME", "English")
crypto$Date <- as.Date(crypto$Date, format = "%b %d, %Y")
#head(crypto$Date)
class(crypto$Date)
#1.5. Dodatkowa kolumna Rate
crypto$Rate <- c(NA, diff(crypto$Close) / head(crypto$Close, -1))
#1.6. Rate malejąco
crypto <- crypto[order(crypto$Rate, decreasing = TRUE), ]
# library(dplyr)
# crypto <- crypto %>% arrange(desc(Rate))
head(crypto)

```
Zad. 2
```{r}
albums <- read.csv("albums.csv")
head(albums)
library(dplyr)
# liczba wierszy i kolumn
dim(albums)
# struktura danych
str(albums)
# sprawdzenie braków danych
albums %>%
  summarise(across(everything(), ~ sum(is.na(.))))
# liczba albumów na artystę
albums %>%
  group_by(artist_id) %>%
  summarise(n_albums = n()) %>%
  arrange(desc(n_albums))
# liczba albumów w każdym gatunku
albums %>%
  group_by(genre) %>%
  summarise(n_albums = n()) %>%
  arrange(desc(n_albums))
# średnia, mediana, min/max ocen mtv
albums %>%
  summarise(
    mean_mtv_critic = mean(mtv_critic, na.rm = TRUE),
    median_mtv_critic = median(mtv_critic, na.rm = TRUE),
    min_mtv_critic = min(mtv_critic, na.rm = TRUE),
    max_mtv_critic = max(mtv_critic, na.rm = TRUE)
  )
# średnia, mediana, min/max ocen music_maniac_critic
albums %>%
  summarise(
    mean_music_maniac_critic = mean(music_maniac_critic, na.rm = TRUE),
    median_music_maniac_critic = median(music_maniac_critic, na.rm = TRUE),
    min_music_maniac_critic = min(music_maniac_critic, na.rm = TRUE),
    max_music_maniac_critic = max(music_maniac_critic, na.rm = TRUE)
  )
# średnia, mediana, min/max ocen music_maniac_critic
albums %>%
  summarise(
    mean_music_maniac_critic = mean(music_maniac_critic, na.rm = TRUE),
    median_music_maniac_critic = median(music_maniac_critic, na.rm = TRUE),
    min_music_maniac_critic = min(music_maniac_critic, na.rm = TRUE),
    max_music_maniac_critic = max(music_maniac_critic, na.rm = TRUE)
  )

```
Zad. 3
```{r}
suicides <- readRDS("suicides.rds")
head(suicides)
library(dplyr)

#3.1 Podsumowanie średnie samobójstwa na 100k w latach 1985-2016
suicides_summary <- suicides %>%
  #filter(year >= 1985, year <= 2016) %>%
  group_by(country) %>%
  summarise(
    avg_suicides_per_100k = mean(suicides.100k.pop, na.rm = TRUE)
  ) %>%
  ungroup()
# Top 5 krajów z największą liczbą samobójstw na 100k
top5 <- suicides_summary %>%
  arrange(desc(avg_suicides_per_100k)) %>%
  slice_head(n = 5)
# Top 5 krajów z najmniejszą liczbą samobójstw na 100k
bottom5 <- suicides_summary %>%
  arrange(avg_suicides_per_100k) %>%
  slice_head(n = 5)
# Wyświetlenie wyników
top5
bottom5

#3.2 Łączna liczba samobójstw na 100k dla każdego roku
suicides_by_year <- suicides %>%
  #filter(year == 2012) %>% #w celu sprawdzenia np. dla 2012
  group_by(year) %>%
  summarise(
    total_suicides = sum(suicides_no, na.rm = TRUE),
    total_population = sum(population, na.rm = TRUE),
    suicides_per_100k = total_suicides / total_population * 100000,
    .groups = "drop"
  ) 
# wynik
suicides_by_year
#3.3 Łączna liczba samobójstw na 100k w podziale na płeć i wiek
suicides_by_sex_age <- suicides %>%
  group_by(sex, age) %>%
  summarise(
    total_suicides = sum(suicides_no, na.rm = TRUE),
    total_population = sum(population, na.rm = TRUE),
    suicides_per_100k = total_suicides / total_population * 100000,
    .groups = "drop"
  ) 
suicides_by_sex_age

#3.4: Top 3 kraje z największą liczbą samobójstw w każdym roku
top3_countries_by_year <- suicides %>%
  group_by(year, country) %>%
  summarise(
    total_suicides = sum(suicides_no, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(year) %>%
  arrange(year, desc(total_suicides)) %>%
  slice_head(n = 3) %>%
  ungroup()

# wynik
top3_countries_by_year

#3.5 Kraj z największą / najmniejszą zmianą ilości samobójstw w ciągu roku
suicides_change <- suicides %>%
  group_by(country) %>%
  summarise(
    max_suicides_per_100k = max(suicides.100k.pop, na.rm = TRUE),
    min_suicides_per_100k = min(suicides.100k.pop, na.rm = TRUE),
    change = max_suicides_per_100k - min_suicides_per_100k,
    .groups = "drop"
  ); suicides_change

# Kraj z największą zmianą
max_country_change <- suicides_change %>%
  arrange(desc(change)) %>%
  slice_head(n=1)
# Kraj z najmniejszą zmianą
min_country_change <- suicides_change %>%
  arrange(change) %>%
  slice_head(n=1)

# Wyniki
max_country_change
min_country_change
```